export const chapters = [
  "Characteristics of Life",
  "Chemistry of Life",
  "The Biosphere",
  "Ecosystems",
  "Population Ecology",
  "Community Ecology",
  "Human Impact",
  "Cell Structure and Function",
  "Metabolism and Photosynthesis",
  "Cellular Respiration",
  "Cell Cycle",
  "Meiosis and Inheritance",
  "DNA Structure and Function",
  "Gene Expression and Regulation",
  "The Human Genome",
  "Biotechnology",
  "Darwin's Theory of Evolution",
  "Evolution of Populations",
  "Classification",
  "History of Life",
];
